### ISSUE TITLE
Initial window size is too small

### ISSUE THREAD

**Issue by hurra** [jo-hannes/Aqua-mixtura#3]
When starting the application the initial window size is to small, see attached screenshot
![image](https://github.com/user-attachments/assets/28fc4ab0-6570-44ec-ab13-9f1cb7754299)

Either remeber the last windows size or maybe just make the initial window a little bigger?
Mabye just resize the collumns `Name`, `Created` and `Modified`?

**Comment by jo-hannes** [comment]
Fixed with commit: 2c235e2fb17962588d13fb512f345bb9bfd9c247
It will resize all columns to fit their contents.
